### ISSUE TITLE
find.exe do not follows DFS links

### ISSUE THREAD

**Issue by Picar66** [amekkawi/diskusagereports#4]
DFS Links are "FILE_ATTRIBUTE_REPARSE_POINT" AND "FILE_ATTRIBUTE_DIRECTORY". Thus needed to be mentioned as Directory to follow.

**Comment by amekkawi** [comment]
I actually consider those soft links that should not be followed, but I could add a flag to follow reparse points if they also have the directory attribute.

**Comment by Picar66** [comment]
Microsoft DFS Links are types of softlinks but links to other UNC Pathes instead of other local pathes.
normaly this is invisible for users, they see it as "links" or normal Directory.
i think it is i good idea to bring this extra handling with a option flag. so every user could use it or not.

**Comment by amekkawi** [comment]
Please try the -r option using the find.exe from https://github.com/amekkawi/diskusagereports/blob/5862cc3434fea13d9907c707eca0a2b14f7851d7/scripts/find.exe?raw=true

**Comment by Picar66** [comment]
Works great.
Thank you
